import type { HomeAssistant } from "./types";

const en = {
  card_name: "THOR Wallbox",
  card_description: "Status, power, session and controls of a Growatt THOR wallbox.",
  no_device: "Pick the wallbox in the card editor.",
  device_not_found: "Wallbox not found: check the device in the card editor.",
  plug_in: "Plug in the car to start",
  car_connected: "Car connected",
  waiting_surplus: "Waiting for surplus",
  waiting_slot: "Waiting for the off-peak slot",
  start: "Start charging",
  stop: "Stop",
  unlock: "Unlock connector",
  cancel: "Cancel start",
  charge_mode: "Charge mode",
  locked_note: "Mode and settings can be changed once the session is over and the car is unplugged.",
  energy: "Energy",
  duration: "Duration",
  cost: "Cost",
  last_session: "Last charge",
  scheduled_start: "Scheduled start",
  every_day: "Every day at {time}",
  cable_locked: "Cable locked",
  cable_unlocked: "Cable unlocked",
  surplus_only: "Surplus only",
  grid_import: "Grid import",
  grid_import_power: "Grid import · {power}",
  boost: "Boost · {type}",
  slots: "Off-peak slots",
  warm_up: "Warm-up",
  limit_energy: "Energy limit",
  limit_cost: "Cost limit",
  limit_duration: "Duration limit",
  boost_by: "Smart Boost by {time}",
  done_of: "{done} of {target}",
  fault: "Fault",
  vendor_code: "Vendor code: {code}.",
  fault_hint: "If it persists, contact your installer.",
  offline_title: "Wallbox unreachable",
  offline_text: "It is not connected to the Growatt cloud: data and controls come back once it reconnects.",
  rfid_title: "RFID mode",
  rfid_text: "Start and stop with the card only. Scheduled starts still work.",
  solar: "Solar",
  wallbox: "Wallbox",
  grid: "Grid",
  from_sources: "From solar {solar}, from the grid {grid}.",
  surplus: "Available surplus: {value}.",
  power: "Charging power",
  editor_device_id: "Wallbox",
  editor_name: "Name",
  editor_flow: "Energy flow",
  editor_solar_power: "Solar production",
  editor_home_power: "Home consumption",
  editor_grid_import_power: "Grid import",
  editor_home_includes_wallbox: "Home consumption includes the wallbox",
  editor_content: "Content",
  editor_show_session: "Session",
  editor_show_progress: "Progress",
  editor_show_controls: "Controls",
  editor_show_last_session: "Last charge",
  helper_solar_power: "Power sensors of the inverter, to show where the wallbox power comes from.",
  helper_home_power: "Optional: with it the card works out the solar surplus.",
  helper_home_includes_wallbox: "On when the wallbox is downstream of the home consumption sensor.",
  helper_show_session: "Energy, duration and cost while a session is open.",
  helper_show_progress: "Fast limit or smart Boost energy reached.",
  helper_show_controls: "Start, stop, unlock and charge mode.",
  helper_show_last_session: "While no session is open.",
};

type Strings = typeof en;
export type StringKey = keyof Strings;

const it: Strings = {
  card_name: "THOR Wallbox",
  card_description: "Stato, potenza, sessione e comandi di una wallbox Growatt THOR.",
  no_device: "Scegli la wallbox nell'editor della card.",
  device_not_found: "Wallbox non trovata: controlla il dispositivo nell'editor della card.",
  plug_in: "Collega l'auto per iniziare",
  car_connected: "Auto collegata",
  waiting_surplus: "In attesa di surplus",
  waiting_slot: "In attesa della fascia Off-peak",
  start: "Avvia ricarica",
  stop: "Arresta",
  unlock: "Sblocca connettore",
  cancel: "Annulla avvio",
  charge_mode: "Modalità di ricarica",
  locked_note: "Modalità e impostazioni si cambiano a sessione chiusa, con l'auto scollegata.",
  energy: "Energia",
  duration: "Durata",
  cost: "Costo",
  last_session: "Ultima ricarica",
  scheduled_start: "Avvio programmato",
  every_day: "Ogni giorno alle {time}",
  cable_locked: "Cavo bloccato",
  cable_unlocked: "Cavo sbloccato",
  surplus_only: "Solo surplus",
  grid_import: "Importa da rete",
  grid_import_power: "Importa da rete · {power}",
  boost: "Boost · {type}",
  slots: "Fasce Off-peak",
  warm_up: "Warm-up",
  limit_energy: "Limite di energia",
  limit_cost: "Limite di costo",
  limit_duration: "Limite di durata",
  boost_by: "Boost smart entro le {time}",
  done_of: "{done} di {target}",
  fault: "Guasto",
  vendor_code: "Codice del produttore: {code}.",
  fault_hint: "Se il guasto resta, contatta l'installatore.",
  offline_title: "Wallbox non raggiungibile",
  offline_text: "Non risulta connessa al cloud Growatt: dati e comandi tornano appena si riconnette.",
  rfid_title: "Modalità RFID",
  rfid_text: "Avvio e arresto solo con la tessera. Gli avvii programmati funzionano comunque.",
  solar: "Fotovoltaico",
  wallbox: "Wallbox",
  grid: "Rete",
  from_sources: "Dal fotovoltaico {solar}, dalla rete {grid}.",
  surplus: "Surplus disponibile: {value}.",
  power: "Potenza di ricarica",
  editor_device_id: "Wallbox",
  editor_name: "Nome",
  editor_flow: "Flusso di energia",
  editor_solar_power: "Produzione fotovoltaica",
  editor_home_power: "Consumo della casa",
  editor_grid_import_power: "Prelievo dalla rete",
  editor_home_includes_wallbox: "Il consumo della casa include la wallbox",
  editor_content: "Contenuto",
  editor_show_session: "Sessione",
  editor_show_progress: "Avanzamento",
  editor_show_controls: "Comandi",
  editor_show_last_session: "Ultima ricarica",
  helper_solar_power: "Sensori di potenza dell'inverter, per mostrare da dove arriva l'energia della wallbox.",
  helper_home_power: "Facoltativo: serve a calcolare il surplus fotovoltaico.",
  helper_home_includes_wallbox: "Attivo se la wallbox è a valle del sensore dei consumi della casa.",
  helper_show_session: "Energia, durata e costo mentre una sessione è aperta.",
  helper_show_progress: "Quanto manca al limite Fast o all'energia del Boost smart.",
  helper_show_controls: "Avvio, arresto, sblocco e modalità di ricarica.",
  helper_show_last_session: "Quando nessuna sessione è aperta.",
};

const STRINGS: Record<string, Strings> = { en, it };

/** The UI language: Home Assistant's, or the page's before `hass` is known. */
function language(hass?: HomeAssistant): string {
  const lang = hass?.locale?.language || hass?.language || document.documentElement.lang || navigator.language;
  return (lang || "en").split("-")[0];
}

export function localize(
  hass: HomeAssistant | undefined,
  key: StringKey,
  vars: Record<string, string> = {},
): string {
  let text = (STRINGS[language(hass)] ?? en)[key] ?? en[key];
  for (const [name, value] of Object.entries(vars)) {
    text = text.replace(`{${name}}`, value);
  }
  return text;
}

export function hasString(key: string): key is StringKey {
  return key in en;
}
